apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - name: frontend
        image: christineibrahim/udagram_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2024Mi"
            cpu: "250m"
          limits:
            memory: "5024Mi"
            cpu: "500m"
      restartPolicy: Always